// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR2324FAs0v5KIg0oV9hsNpOmtWFTZlzo',
    appId: '1:126649705528:web:e00b67311e388e6b7ab2cd',
    messagingSenderId: '126649705528',
    projectId: 'science-2c6a7',
    authDomain: 'science-2c6a7.firebaseapp.com',
    storageBucket: 'science-2c6a7.appspot.com',
    measurementId: 'G-ZL728QSXMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlfd1YPjnw7oYuvBRZ8DJDF5b9T54uxKM',
    appId: '1:126649705528:android:bf10f9cff52d2e8d7ab2cd',
    messagingSenderId: '126649705528',
    projectId: 'science-2c6a7',
    storageBucket: 'science-2c6a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApOIRbpNB0zMpI1yrL8mc0e1RVgt2klEA',
    appId: '1:126649705528:ios:9629fc99f5a436fa7ab2cd',
    messagingSenderId: '126649705528',
    projectId: 'science-2c6a7',
    storageBucket: 'science-2c6a7.appspot.com',
    iosClientId: '126649705528-868n6n1l9dgr3ll542ifb8mpjq7aaqk4.apps.googleusercontent.com',
    iosBundleId: 'com.xcodeteam.science',
  );
}
